### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by hacret** [qmlcode/qml#140]
Python 3.9.9 (main, Dec  1 2021, 16:36:40)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import qml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/user/kijsdc/.local/lib/python3.9/site-packages/qml/__init__.py", line 37, in <module>
    from .compound import Compound
  File "/user/kijsdc/.local/lib/python3.9/site-packages/qml/compound.py", line 30, in <module>
    from .representations import generate_coulomb_matrix
  File "/user/kijsdc/.local/lib/python3.9/site-packages/qml/representations.py", line 28, in <module>
    from .frepresentations import fgenerate_coulomb_matrix
ImportError: /user/kijsdc/.local/lib/python3.9/site-packages/qml/frepresentations.cpython-39-x86_64-linux-gnu.so: undefined symbol: dsyev_

I need your help. please help me...

**Comment by charnley** [comment]
Please note that further development for the QML package is now happening on the [qmlcode/qmllib](https://github.com/qmlcode/qmllib) repository. ``qmllib`` is a port of the QML's Fortran core functionality with fewer dependencies and numpy 2.0 compatibility. You are encouraged to open any future issues or pull requests there.
